### ISSUE TITLE
IAssemblyFixture fails

### ISSUE THREAD

**Issue by johnknoop** [tomaszeman/Xunit.Extensions.Ordering#3]
This is my test class:

```csharp
public class MyTestClass : IAssemblyFixture<MyFixture>
{
	private readonly MyFixture _fixture;

	public MyTest(MyFixture fixture)
	{
		_fixture = fixture;
	}

	[Fact]
	public async Task MyTest()
	{
		// test code omitted
	}
}
```

When I run the test, it fails with this exception:

> The following constructor parameters did not have matching fixture data: MyFixture fixture
>  Exception doesn't have a stacktrace

The `MyFixture` class implements `IDisposable`.

If I replace `IAssemblyFIxture` with `IClassFixture`, everything works.

**Comment by tomaszeman** [comment]
Pls register TestFramework replacement. Sorry if it isn't clear from docs.

[assembly: TestFramework("Xunit.Extensions.Ordering.TestFramework", "Xunit.Extensions.Ordering")]

**Comment by johnknoop** [comment]
I understand. Where is the best way to put that in a .Net Core project? (they don't have an AssemblyInfo file by default)

**Comment by tomaszeman** [comment]
It's up to you. I use AssemblyInfo.cs file.

**Comment by johnknoop** [comment]
This seemed to do the trick. Thanks!
